name: Parallel Job Runner

on: [push]

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Job 1
        run: echo "Running Job 1 inside container"

  job2:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Job 2
        run: echo "Running Job 2 inside container"

  job3:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Job 3
        run: echo "Running Job 3 inside container"
